"""Local Title engine using original Desert Ant Labs MLX weights.

Prompt and card parsing adapted from Desert Ant Labs' Title.swift.
Copyright 2026 Desert Ant Labs B.V. Source-Available License v1.0.
"""
import argparse
import hmac
import json
import secrets
from http.server import BaseHTTPRequestHandler, HTTPServer
from pathlib import Path

from huggingface_hub import snapshot_download
from mlx_lm import generate, load
from mlx_lm.sample_utils import make_sampler

PROMPT = (
    'Write a factual title (3-8 words) and a 1-2 sentence description for this passage.'
    'Be specific enough to identify this passage. No emoji, no hashtags, no hype.'
    'Write in the same language as the passage.\n\nPASSAGE:\n{clip}'
)

def parse_card(raw):
    title, description = '', ''
    for line in raw.splitlines():
        text = line.strip()
        upper = text.upper()
        if upper.startswith('TITLE:'):
            title = text[6:].strip()
        elif upper.startswith('DESCRIPTION:'):
            description = text[12:].strip()
        elif upper.startswith('DESC:'):
            description = text[5:].strip()
        elif not title and text:
            title = text
    return {'title': title, 'description': description}

def main():
    parser = argparse.ArgumentParser(description='Title by Desert Ant Labs, local web demo engine')
    parser.add_argument('--port', type=int, default=8768)
    parser.add_argument('--token', default=None, help='Optional pairing token; a random token is generated by default')
    args = parser.parse_args()
    token = args.token or secrets.token_urlsafe(24)
    print('Loading Title v0.1.0 by Desert Ant Labs. First use downloads about 294 MB.', flush=True)
    directory = snapshot_download('desert-ant-labs/title', revision='v0.1.0', allow_patterns=['*.json', '*.safetensors', '*.jinja'])
    model, tokenizer = load(directory)
    site = Path(__file__).resolve().parents[1] / 'site'

    class Handler(BaseHTTPRequestHandler):
        def cors(self):
            origin = self.headers.get('Origin', '')
            if origin == 'https://shubin123.github.io' or origin.startswith('http://127.0.0.1:') or origin.startswith('http://localhost:'):
                self.send_header('Access-Control-Allow-Origin', origin)
                self.send_header('Vary', 'Origin')
            self.send_header('Access-Control-Allow-Methods', 'GET, POST, OPTIONS')
            self.send_header('Access-Control-Allow-Headers', 'Content-Type, X-Pairing-Token')
            self.send_header('Access-Control-Allow-Private-Network', 'true')

        def reply(self, code, body):
            data = json.dumps(body).encode()
            self.send_response(code)
            self.cors()
            self.send_header('Content-Type', 'application/json')
            self.send_header('Content-Length', str(len(data)))
            self.send_header('Cache-Control', 'no-store')
            self.end_headers()
            self.wfile.write(data)

        def do_OPTIONS(self):
            self.send_response(204)
            self.cors()
            self.end_headers()

        def do_GET(self):
            if self.path == '/health':
                return self.reply(200, {'model': 'Title', 'revision': 'v0.1.0', 'ready': True})
            name = self.path.split('?', 1)[0].lstrip('/') or 'index.html'
            target = (site / name).resolve()
            if not target.is_relative_to(site) or not target.is_file():
                return self.reply(404, {'error': 'Not found'})
            data = target.read_bytes()
            self.send_response(200)
            content_type = {'.html': 'text/html', '.js': 'text/javascript', '.css': 'text/css', '.svg': 'image/svg+xml'}.get(target.suffix, 'application/octet-stream')
            self.send_header('Content-Type', content_type)
            self.send_header('Content-Length', str(len(data)))
            self.end_headers()
            self.wfile.write(data)

        def do_POST(self):
            if self.path != '/describe':
                return self.reply(404, {'error': 'Not found'})
            if not hmac.compare_digest(self.headers.get('X-Pairing-Token', ''), token):
                return self.reply(401, {'error': 'Paste the pairing token printed by your local engine.'})
            try:
                length = int(self.headers.get('Content-Length', '0'))
                if length <= 0 or length > 64000:
                    return self.reply(400, {'error': 'Passage is missing or too large.'})
                text = json.loads(self.rfile.read(length)).get('text')
                if not isinstance(text, str) or not text.strip() or len(text) > 12000:
                    return self.reply(400, {'error': 'Enter a passage of up to 12,000 characters.'})
                prompt = tokenizer.apply_chat_template([{'role': 'user', 'content': PROMPT.replace('{clip}', text)}], tokenize=False, add_generation_prompt=True)
                raw = generate(model, tokenizer, prompt=prompt, max_tokens=96, sampler=make_sampler(temp=0), verbose=False)
                card = parse_card(raw)
                if not card['title']:
                    return self.reply(422, {'error': 'The model returned no title. Try a shorter passage.'})
                self.reply(200, card)
            except (ValueError, json.JSONDecodeError):
                self.reply(400, {'error': 'Invalid request.'})
            except Exception as error:
                self.reply(500, {'error': str(error)})

        def log_message(self, format, *args):
            # Request bodies and generated cards are never logged.
            print(format % args, flush=True)

    server = HTTPServer(('127.0.0.1', args.port), Handler)
    print(f'Engine ready. Open http://127.0.0.1:{args.port}/ or the GitHub Pages demo.', flush=True)
    print(f'Pairing token: {token}', flush=True)
    try:
        server.serve_forever()
    except KeyboardInterrupt:
        pass
    finally:
        server.server_close()

if __name__ == '__main__':
    main()
